
-- Add GSTIN to customers
ALTER TABLE customers ADD COLUMN IF NOT EXISTS gstin TEXT;

-- Add GST fields to bills
ALTER TABLE bills ADD COLUMN IF NOT EXISTS customer_gstin TEXT;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS igst_amount NUMERIC DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS is_igst BOOLEAN DEFAULT false;

-- Add HSN code to bill_items
ALTER TABLE bill_items ADD COLUMN IF NOT EXISTS hsn_code TEXT DEFAULT '7113';
