// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://calzzyiqwaskxmbpbngm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhbHp6eWlxd2Fza3htYnBibmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTA3MjUsImV4cCI6MjA2MDIyNjcyNX0.2CZMMfEB_elbnDXoA7fKT2fmeWk_dcLJ1J9hyakzDqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});